<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "annuaire_bvb"
 *
 * Auto generated by Extension Builder 2017-06-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'AnnuaireBVB',
	'description' => 'Recueil annuel contenant des renseignements statistiques, des notices biographiques, etc., sur l\'année précédente, ou des indications sur l\'état du personnel, les membres d\'une société, etc.',
	'category' => 'plugin',
	'author' => 'Bettini Emile, Villeneuve Michael, Brones Alexis',
	'author_email' => 'emile.bettini@etu.u-bordeaux.fr, michael.villeneuve@etu.u-bordeaux.fr, alexis.brones@etu.u-bordeaux.fr',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);